using ColleagueInt.RTW.Database.Constants;
using ColleagueInt.RTW.Database.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using AppSettings = ColleagueInt.RTW.Database.Entities.AppSettings;

namespace ColleagueInt.RTW.Database.Seeding
{
    public static partial class ModelBuilderExtensions
    {
        public static void SeedData(this ModelBuilder modelBuilder)
        {
            SeedStatusData(modelBuilder);
            SeedStagesData(modelBuilder);
            SeedIncidentDetails(modelBuilder);
            SeedDocumentTypeData(modelBuilder);
            SeedCountriesData(modelBuilder);
            SeedFilterData(modelBuilder);
            SeedAppSettingsData(modelBuilder);

        }

        private static void SeedAppSettingsData(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AppSettings>().HasData(
                 new AppSettings { Id = 1, Type = "bool", Key = "HCM-To-RTW-OutboundFlow", Value = "FALSE", Description = "Flag to determine whether there is a downtime for outbound service to RTW" },
                 new AppSettings { Id = 2, Type = "dateTime", Key = "HCM-To-RTW-OutboundFlow-DownTime-Start", Value = "2022-05-02 21:30:00", Description = "Outbound service downtime starts from this timestamp if the downtime flag is true" },
                 new AppSettings { Id = 3, Type = "dateTime", Key = "HCM-To-RTW-OutboundFlow-DownTime-End", Value = "2022-05-02 21:35:00", Description = "Outbound service downtime ends from this timestamp if the downtime flag is true" },
                 new AppSettings { Id = 4, Type = "bool", Key = "RTW-To-HCM-InboundFlow", Value = "FALSE", Description = "Flag to determine whether there is a downtime for inbound service to HCM" },
                 new AppSettings { Id = 5, Type = "dateTime", Key = "RTW-To-HCM-InboundFlow-DownTime-Start", Value = "2022-05-02 22:00:00", Description = "Inbound service downtime starts from this timestamp if the downtime flag is true" },
                 new AppSettings { Id = 6, Type = "dateTime", Key = "RTW-To-HCM-InboundFlow-DownTime-End", Value = "2022-05-02 22:10:00", Description = "Inbound service downtime ends from this timestamp if the downtime flag is true" },
                 new AppSettings { Id = 7, Type = "string", Key = "Refresh-HCM-Visa-Approved-Colleagues-Daily-Time-Hours", Value = "22", Description = "Set a specific time in hours to read visa approved colleagues from HCM or set it to blank to stop the service" },
                 new AppSettings { Id = 8, Type = "dateTime", Key = "Last-Time-HCM-Visa-Approved-Colleagues-Refreshed-At", Value = "2022-05-24 21:30:00", Description = "Last visa approved colleagues details read from HCM at" },
                 new AppSettings { Id = 9, Type = "bool", Key = "RTW-To-HCM-InboundPastportUpdate", Value = "TRUE", Description = "Update NFC chip passport images active TRUE/FALSE" },
                 new AppSettings { Id = 10, Type = "dateTime", Key = "RTW-To-HCM-InboundPastportUpdateCutOffTime", Value = "2022-10-19 11:15:00", Description = "Passport image update cut off date and time" }
                 );
        }

        private static void SeedFilterData(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FilterData>().HasData(
                new FilterData { Id = 1, BusinessUnitName = "Argos Customer Management Centres", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 2, BusinessUnitName = "Argos Distribution", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 3, BusinessUnitName = "Argos Local Fulfilment Centres", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 4, BusinessUnitName = "Argos Retail", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 5, BusinessUnitName = "Retail", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 6, BusinessUnitName = "Corporate Affairs", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 7, BusinessUnitName = "Corporate Services", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 8, BusinessUnitName = "Digital", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 9, BusinessUnitName = "Executives", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 10, BusinessUnitName = "Finance & Business Development", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 11, BusinessUnitName = "Food Commercial", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 12, BusinessUnitName = "Group HR", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 13, BusinessUnitName = "Habitat", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 14, BusinessUnitName = "Logistics", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 15, BusinessUnitName = "Marketing", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 16, BusinessUnitName = "Nectar", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 17, BusinessUnitName = "Nectar 360 Ltd", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 18, BusinessUnitName = "Non Food", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 19, BusinessUnitName = "Property", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 20, BusinessUnitName = "Sainsbury's Tech", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 21, BusinessUnitName = "GM&C", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 22, BusinessUnitName = "HR", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 23, BusinessUnitName = "CFO Division", Description = "Include colleagues matching the filter criteria." },
                new FilterData { Id = 24, BusinessUnitName = "Sainsbury's Bank", Description = "Include colleagues matching the filter criteria." }
                );
        }

        private static void SeedCountriesData(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Country>().HasData(
                new Country { Id = 1, HCMCountryCode = "MHR_ALANAD_ISLANDS", HCMCountryName = "Alanad Islands", RTWCountryCode = "ALA", RTWCountryName = "Aaland Islands" },
                new Country { Id = 2, HCMCountryCode = "AF", HCMCountryName = "Afghan", RTWCountryCode = "AFG", RTWCountryName = "Afghanistan" },
                new Country { Id = 3, HCMCountryCode = "AL", HCMCountryName = "Albanian", RTWCountryCode = "ALB", RTWCountryName = "Albania" },
                new Country { Id = 4, HCMCountryCode = "DZ", HCMCountryName = "Algerian", RTWCountryCode = "DZA", RTWCountryName = "Algeria" },
                new Country { Id = 5, HCMCountryCode = "AD", HCMCountryName = "Andorran", RTWCountryCode = "AND", RTWCountryName = "Andorra" },
                new Country { Id = 6, HCMCountryCode = "AO", HCMCountryName = "Angolan", RTWCountryCode = "AGO", RTWCountryName = "Angola" },
                new Country { Id = 7, HCMCountryCode = "MHR_AGUILLAN", HCMCountryName = "Anguillan", RTWCountryCode = "AIA", RTWCountryName = "Anguilla" },
                new Country { Id = 8, HCMCountryCode = "MHR_ANTARTICAN", HCMCountryName = "Antartican", RTWCountryCode = "ATA", RTWCountryName = "Antarctica" },
                new Country { Id = 9, HCMCountryCode = "AG", HCMCountryName = "Antiguan", RTWCountryCode = "ATG", RTWCountryName = "Antigua & Barbuda" },
                new Country { Id = 10, HCMCountryCode = "AR", HCMCountryName = "Argentine", RTWCountryCode = "ARG", RTWCountryName = "Argentina" },
                new Country { Id = 11, HCMCountryCode = "AM", HCMCountryName = "Armenian", RTWCountryCode = "ARM", RTWCountryName = "Armenia" },
                new Country { Id = 12, HCMCountryCode = "MHR_ARUBAN", HCMCountryName = "Aruban", RTWCountryCode = "ABW", RTWCountryName = "Aruba" },
                new Country { Id = 13, HCMCountryCode = "AU", HCMCountryName = "Australian", RTWCountryCode = "AUS", RTWCountryName = "Australia" },
                new Country { Id = 14, HCMCountryCode = "AT", HCMCountryName = "Austrian", RTWCountryCode = "AUT", RTWCountryName = "Austria" },
                new Country { Id = 15, HCMCountryCode = "AZ", HCMCountryName = "Azerbaijani", RTWCountryCode = "AZE", RTWCountryName = "Azerbaijan" },
                new Country { Id = 16, HCMCountryCode = "BS", HCMCountryName = "Bahamian", RTWCountryCode = "BHS", RTWCountryName = "Bahamas" },
                new Country { Id = 17, HCMCountryCode = "BH", HCMCountryName = "Bahraini", RTWCountryCode = "BHR", RTWCountryName = "Bahrain" },
                new Country { Id = 18, HCMCountryCode = "BD", HCMCountryName = "Bangladeshi", RTWCountryCode = "BGD", RTWCountryName = "Bangladesh" },
                new Country { Id = 19, HCMCountryCode = "BB", HCMCountryName = "Barbadian", RTWCountryCode = "BRB", RTWCountryName = "Barbados" },
                new Country { Id = 20, HCMCountryCode = "BY", HCMCountryName = "Belarusian", RTWCountryCode = "BLR", RTWCountryName = "Belarus" },
                new Country { Id = 21, HCMCountryCode = "BE", HCMCountryName = "Belgian", RTWCountryCode = "BEL", RTWCountryName = "Belgium" },
                new Country { Id = 22, HCMCountryCode = "BZ", HCMCountryName = "Belizean", RTWCountryCode = "BLZ", RTWCountryName = "Belize" },
                new Country { Id = 23, HCMCountryCode = "BJ", HCMCountryName = "Beninese", RTWCountryCode = "BEN", RTWCountryName = "Benin" },
                new Country { Id = 24, HCMCountryCode = "BM", HCMCountryName = "Bermudan", RTWCountryCode = "BMU", RTWCountryName = "Bermuda" },
                new Country { Id = 25, HCMCountryCode = "BT", HCMCountryName = "Bhutanese", RTWCountryCode = "BTN", RTWCountryName = "Bhutan" },
                new Country { Id = 26, HCMCountryCode = "BO", HCMCountryName = "Bolivian", RTWCountryCode = "BOL", RTWCountryName = "Bolivia" },
                new Country { Id = 27, HCMCountryCode = "BA", HCMCountryName = "Bosnian", RTWCountryCode = "BIH", RTWCountryName = "Bosnia & Herzegovina" },
                new Country { Id = 28, HCMCountryCode = "BW", HCMCountryName = "Botswana", RTWCountryCode = "BWA", RTWCountryName = "Botswana" },
                new Country { Id = 29, HCMCountryCode = "MHR_BOUVET_ISLANDS", HCMCountryName = "Bouvet Islands", RTWCountryCode = "BVT", RTWCountryName = "Bouvet Island" },
                new Country { Id = 30, HCMCountryCode = "BR", HCMCountryName = "Brazilian", RTWCountryCode = "BRA", RTWCountryName = "Brazil" },
                new Country { Id = 31, HCMCountryCode = "MHR_BRITISH_INDIAN_TERRITORY", HCMCountryName = "British Indian Ocean Territory", RTWCountryCode = "IOT", RTWCountryName = "British Indian Ocean Territory" },
                new Country { Id = 32, HCMCountryCode = "BN", HCMCountryName = "Bruneian", RTWCountryCode = "BRN", RTWCountryName = "Brunei Darussalam" },
                new Country { Id = 33, HCMCountryCode = "BG", HCMCountryName = "Bulgarian", RTWCountryCode = "BGR", RTWCountryName = "Bulgaria" },
                new Country { Id = 34, HCMCountryCode = "BF", HCMCountryName = "Burkinabe", RTWCountryCode = "BFA", RTWCountryName = "Burkina Faso" },
                new Country { Id = 35, HCMCountryCode = "BI", HCMCountryName = "Burundian", RTWCountryCode = "BDI", RTWCountryName = "Burundi" },
                new Country { Id = 36, HCMCountryCode = "KH", HCMCountryName = "Cambodian", RTWCountryCode = "KHM", RTWCountryName = "Cambodia" },
                new Country { Id = 37, HCMCountryCode = "CM", HCMCountryName = "Cameroonian", RTWCountryCode = "CMR", RTWCountryName = "Cameroon" },
                new Country { Id = 38, HCMCountryCode = "CA", HCMCountryName = "Canadian", RTWCountryCode = "CAN", RTWCountryName = "Canada" },
                new Country { Id = 39, HCMCountryCode = "CV", HCMCountryName = "Cape Verdean", RTWCountryCode = "CPV", RTWCountryName = "Cape Verde" },
                new Country { Id = 40, HCMCountryCode = "MHR_CAYMANIAN", HCMCountryName = "Caymanian", RTWCountryCode = "CYM", RTWCountryName = "Cayman Islands" },
                new Country { Id = 41, HCMCountryCode = "CF", HCMCountryName = "Central African", RTWCountryCode = "CAF", RTWCountryName = "Central African Republic" },
                new Country { Id = 42, HCMCountryCode = "CL", HCMCountryName = "Chilean", RTWCountryCode = "CHL", RTWCountryName = "Chile" },
                new Country { Id = 43, HCMCountryCode = "CN", HCMCountryName = "Chinese", RTWCountryCode = "CHN", RTWCountryName = "China" },
                new Country { Id = 44, HCMCountryCode = "MHR_CHRISTMAS_ISLAND", HCMCountryName = "Christmas Islander", RTWCountryCode = "CXR", RTWCountryName = "Christmas Island" },
                new Country { Id = 45, HCMCountryCode = "MHR_COCOS_ISLANDER", HCMCountryName = "Cocos Islander", RTWCountryCode = "CCK", RTWCountryName = "Cocos (Keeling) Islands" },
                new Country { Id = 46, HCMCountryCode = "CO", HCMCountryName = "Colombian", RTWCountryCode = "COL", RTWCountryName = "Colombia" },
                new Country { Id = 47, HCMCountryCode = "KM", HCMCountryName = "Comoran", RTWCountryCode = "COM", RTWCountryName = "Comoros" },
                new Country { Id = 48, HCMCountryCode = "CG", HCMCountryName = "Congolese (Republic)", RTWCountryCode = "COG", RTWCountryName = "Congo, Republic of" },
                new Country { Id = 49, HCMCountryCode = "CD", HCMCountryName = "Congolese (Democratic Republic)", RTWCountryCode = "COD", RTWCountryName = "Congo, Democratic Republic" },
                new Country { Id = 50, HCMCountryCode = "MHR_COOK_ISLAND", HCMCountryName = "Cook Islander", RTWCountryCode = "COK", RTWCountryName = "Cook Islands" },
                new Country { Id = 51, HCMCountryCode = "CR", HCMCountryName = "Costa Rican", RTWCountryCode = "CRI", RTWCountryName = "Costa Rica" },
                new Country { Id = 52, HCMCountryCode = "11", HCMCountryName = "Unknown", RTWCountryCode = "CIV", RTWCountryName = "Cte d'Ivoire" },
                new Country { Id = 53, HCMCountryCode = "HR", HCMCountryName = "Croatian", RTWCountryCode = "HRV", RTWCountryName = "Croatia (local name: Hrvatska)" },
                new Country { Id = 54, HCMCountryCode = "CU", HCMCountryName = "Cuban", RTWCountryCode = "CUB", RTWCountryName = "Cuba" },
                new Country { Id = 55, HCMCountryCode = "CY", HCMCountryName = "Cypriot", RTWCountryCode = "CYP", RTWCountryName = "Cyprus" },
                new Country { Id = 56, HCMCountryCode = "CZ", HCMCountryName = "Czech", RTWCountryCode = "CZE", RTWCountryName = "Czech Republic" },
                new Country { Id = 57, HCMCountryCode = "DK", HCMCountryName = "Danish", RTWCountryCode = "DNK", RTWCountryName = "Denmark" },
                new Country { Id = 58, HCMCountryCode = "DJ", HCMCountryName = "Djiboutian", RTWCountryCode = "DJI", RTWCountryName = "Djibouti" },
                new Country { Id = 59, HCMCountryCode = "DM", HCMCountryName = "Dominican (Dominica)", RTWCountryCode = "DMA", RTWCountryName = "Dominica" },
                new Country { Id = 60, HCMCountryCode = "DO", HCMCountryName = "Dominican (Dominican Republic)", RTWCountryCode = "DOM", RTWCountryName = "Dominican Republic" },
                new Country { Id = 61, HCMCountryCode = "EC", HCMCountryName = "Ecuadorian", RTWCountryCode = "ECU", RTWCountryName = "Ecuador" },
                new Country { Id = 62, HCMCountryCode = "EG", HCMCountryName = "Egyptian", RTWCountryCode = "EGY", RTWCountryName = "Egypt" },
                new Country { Id = 63, HCMCountryCode = "SV", HCMCountryName = "Salvadoran", RTWCountryCode = "SLV", RTWCountryName = "El Salvador" },
                new Country { Id = 64, HCMCountryCode = "GQ", HCMCountryName = "Equatorial Guinean", RTWCountryCode = "GNQ", RTWCountryName = "Equatorial Guinea" },
                new Country { Id = 65, HCMCountryCode = "ER", HCMCountryName = "Eritrean", RTWCountryCode = "ERI", RTWCountryName = "Eritrea" },
                new Country { Id = 66, HCMCountryCode = "EE", HCMCountryName = "Estonian", RTWCountryCode = "EST", RTWCountryName = "Estonia" },
                new Country { Id = 67, HCMCountryCode = "ET", HCMCountryName = "Ethiopian", RTWCountryCode = "ETH", RTWCountryName = "Ethiopia" },
                new Country { Id = 68, HCMCountryCode = "MHR_FALKAND ISLAND", HCMCountryName = "Falkand Islander", RTWCountryCode = "FLK", RTWCountryName = "Falkland Islands (Malvinas)" },
                new Country { Id = 69, HCMCountryCode = "MHR_FAROESE", HCMCountryName = "Faroese", RTWCountryCode = "FRO", RTWCountryName = "Faroe Islands" },
                new Country { Id = 70, HCMCountryCode = "FJ", HCMCountryName = "Fijian", RTWCountryCode = "FJI", RTWCountryName = "Fiji" },
                new Country { Id = 71, HCMCountryCode = "FI", HCMCountryName = "Finnish", RTWCountryCode = "FIN", RTWCountryName = "Finland" },
                new Country { Id = 72, HCMCountryCode = "FR", HCMCountryName = "French", RTWCountryCode = "FRA", RTWCountryName = "France" },
                new Country { Id = 73, HCMCountryCode = "MHR_FRENCH_GUIANESE", HCMCountryName = "French Guianese", RTWCountryCode = "ATF", RTWCountryName = "Franch Southern Territories" },
                new Country { Id = 74, HCMCountryCode = "MHR_FRENCH_POLYNESIAN", HCMCountryName = "French Polynesian", RTWCountryCode = "GUF", RTWCountryName = "French Guiana" },
                new Country { Id = 75, HCMCountryCode = "MHR_F_SOUTHERN_TERRITORIES", HCMCountryName = "French Southern Territories", RTWCountryCode = "PYF", RTWCountryName = "French Polynesia" },
                new Country { Id = 76, HCMCountryCode = "GA", HCMCountryName = "Gabonese", RTWCountryCode = "GAB", RTWCountryName = "Gabon" },
                new Country { Id = 77, HCMCountryCode = "GM", HCMCountryName = "Gambian", RTWCountryCode = "GMB", RTWCountryName = "Gambia" },
                new Country { Id = 78, HCMCountryCode = "GE", HCMCountryName = "Georgian", RTWCountryCode = "GEO", RTWCountryName = "Georgia" },
                new Country { Id = 79, HCMCountryCode = "DE", HCMCountryName = "German", RTWCountryCode = "DEU", RTWCountryName = "Germany" },
                new Country { Id = 80, HCMCountryCode = "GH", HCMCountryName = "Ghanaian", RTWCountryCode = "GHA", RTWCountryName = "Ghana" },
                new Country { Id = 81, HCMCountryCode = "GI", HCMCountryName = "Gibraltarian", RTWCountryCode = "GIB", RTWCountryName = "Gibraltar" },
                new Country { Id = 82, HCMCountryCode = "GR", HCMCountryName = "Greek", RTWCountryCode = "GRC", RTWCountryName = "Greece" },
                new Country { Id = 83, HCMCountryCode = "MHR_GREENLANDIC", HCMCountryName = "Greenlandic", RTWCountryCode = "GRL", RTWCountryName = "Greenland" },
                new Country { Id = 84, HCMCountryCode = "GD", HCMCountryName = "Grenadian", RTWCountryCode = "GRD", RTWCountryName = "Grenada" },
                new Country { Id = 85, HCMCountryCode = "MHR_GUADELOUPE", HCMCountryName = "Guadeloupe", RTWCountryCode = "GLP", RTWCountryName = "Guadeloupe" },
                new Country { Id = 86, HCMCountryCode = "MHR_GUAMANIAN", HCMCountryName = "Guamanian", RTWCountryCode = "GUM", RTWCountryName = "Guam" },
                new Country { Id = 87, HCMCountryCode = "GT", HCMCountryName = "Guatemalan", RTWCountryCode = "GTM", RTWCountryName = "Guatemala" },
                new Country { Id = 88, HCMCountryCode = "GN", HCMCountryName = "Guinean (Guinea)", RTWCountryCode = "GIN", RTWCountryName = "Guinea" },
                new Country { Id = 89, HCMCountryCode = "GW", HCMCountryName = "Guinean (Guinea-Bissau)", RTWCountryCode = "GNB", RTWCountryName = "Guinea-Bissau" },
                new Country { Id = 90, HCMCountryCode = "GY", HCMCountryName = "Guyanese", RTWCountryCode = "GUY", RTWCountryName = "Guyana" },
                new Country { Id = 91, HCMCountryCode = "HT", HCMCountryName = "Haitian", RTWCountryCode = "HTI", RTWCountryName = "Haiti" },
                new Country { Id = 92, HCMCountryCode = "MHR_HEARD_AND_MCDONALD", HCMCountryName = "Heard Island and Mcdonald Island", RTWCountryCode = "HMD", RTWCountryName = "Heard & McDonald Islands" },
                new Country { Id = 93, HCMCountryCode = "HN", HCMCountryName = "Honduran", RTWCountryCode = "HND", RTWCountryName = "Honduras" },
                new Country { Id = 94, HCMCountryCode = "MHR_HONGKONGESE", HCMCountryName = "Hongkongese", RTWCountryCode = "HKG", RTWCountryName = "Hong Kong" },
                new Country { Id = 95, HCMCountryCode = "HU", HCMCountryName = "Hungarian", RTWCountryCode = "HUN", RTWCountryName = "Hungary" },
                new Country { Id = 96, HCMCountryCode = "IS", HCMCountryName = "Icelandic", RTWCountryCode = "ISL", RTWCountryName = "Iceland" },
                new Country { Id = 97, HCMCountryCode = "IN", HCMCountryName = "Indian", RTWCountryCode = "IND", RTWCountryName = "India" },
                new Country { Id = 98, HCMCountryCode = "ID", HCMCountryName = "Indonesian", RTWCountryCode = "IDN", RTWCountryName = "Indonesia" },
                new Country { Id = 99, HCMCountryCode = "IR", HCMCountryName = "Iranian", RTWCountryCode = "IRN", RTWCountryName = "Iran" },
                new Country { Id = 100, HCMCountryCode = "IQ", HCMCountryName = "Iraqi", RTWCountryCode = "IRQ", RTWCountryName = "Iraq" },
                new Country { Id = 101, HCMCountryCode = "IE", HCMCountryName = "Irish", RTWCountryCode = "IRL", RTWCountryName = "Ireland" },
                new Country { Id = 102, HCMCountryCode = "IL", HCMCountryName = "Israeli", RTWCountryCode = "ISR", RTWCountryName = "Israel" },
                new Country { Id = 103, HCMCountryCode = "IT", HCMCountryName = "Italian", RTWCountryCode = "ITA", RTWCountryName = "Italy" },
                new Country { Id = 104, HCMCountryCode = "JM", HCMCountryName = "Jamaican", RTWCountryCode = "JAM", RTWCountryName = "Jamaica" },
                new Country { Id = 105, HCMCountryCode = "JP", HCMCountryName = "Japanese", RTWCountryCode = "JPN", RTWCountryName = "Japan" },
                new Country { Id = 106, HCMCountryCode = "JO", HCMCountryName = "Jordanian", RTWCountryCode = "JOR", RTWCountryName = "Jordan" },
                new Country { Id = 107, HCMCountryCode = "KZ", HCMCountryName = "Kazakhstani", RTWCountryCode = "KAZ", RTWCountryName = "Kazakhstan" },
                new Country { Id = 108, HCMCountryCode = "KE", HCMCountryName = "Kenyan", RTWCountryCode = "KEN", RTWCountryName = "Kenya" },
                new Country { Id = 109, HCMCountryCode = "KI", HCMCountryName = "Kiribati", RTWCountryCode = "KIR", RTWCountryName = "Kiribati" },
                new Country { Id = 110, HCMCountryCode = "KR", HCMCountryName = "South Korean", RTWCountryCode = "KOR", RTWCountryName = "Korea" },
                new Country { Id = 111, HCMCountryCode = "KP", HCMCountryName = "North Korean", RTWCountryCode = "PRK", RTWCountryName = "Korea, Democratic People's Republic" },
                new Country { Id = 112, HCMCountryCode = "KV", HCMCountryName = "Kosovar", RTWCountryCode = "RKS", RTWCountryName = "Kosovo" },
                new Country { Id = 113, HCMCountryCode = "KG", HCMCountryName = "Kyrgyzstani", RTWCountryCode = "KGZ", RTWCountryName = "Krygyzstan" },
                new Country { Id = 114, HCMCountryCode = "KW", HCMCountryName = "Kuwaiti", RTWCountryCode = "KWT", RTWCountryName = "Kuwait" },
                new Country { Id = 115, HCMCountryCode = "LA", HCMCountryName = "Laotian", RTWCountryCode = "LAO", RTWCountryName = "Laos" },
                new Country { Id = 116, HCMCountryCode = "LV", HCMCountryName = "Latvian", RTWCountryCode = "LVA", RTWCountryName = "Latvia" },
                new Country { Id = 117, HCMCountryCode = "LB", HCMCountryName = "Lebanese", RTWCountryCode = "LBN", RTWCountryName = "Lebanon" },
                new Country { Id = 118, HCMCountryCode = "LS", HCMCountryName = "Basotho", RTWCountryCode = "LSO", RTWCountryName = "Lesotho" },
                new Country { Id = 119, HCMCountryCode = "LR", HCMCountryName = "Liberian", RTWCountryCode = "LBR", RTWCountryName = "Liberia" },
                new Country { Id = 120, HCMCountryCode = "LY", HCMCountryName = "Libyan", RTWCountryCode = "LBY", RTWCountryName = "Libya" },
                new Country { Id = 121, HCMCountryCode = "LI", HCMCountryName = "Liechtensteiner", RTWCountryCode = "LIE", RTWCountryName = "Liechtenstein" },
                new Country { Id = 122, HCMCountryCode = "LT", HCMCountryName = "Lithuanian", RTWCountryCode = "LTU", RTWCountryName = "Lithuania" },
                new Country { Id = 123, HCMCountryCode = "LU", HCMCountryName = "Luxembourg", RTWCountryCode = "LUX", RTWCountryName = "Luxembourg" },
                new Country { Id = 124, HCMCountryCode = "MHR_MACANESE", HCMCountryName = "Macanese", RTWCountryCode = "MAC", RTWCountryName = "Macau" },
                new Country { Id = 125, HCMCountryCode = "MG", HCMCountryName = "Malagasy", RTWCountryCode = "MDG", RTWCountryName = "Madagascar" },
                new Country { Id = 126, HCMCountryCode = "MW", HCMCountryName = "Malawian", RTWCountryCode = "MWI", RTWCountryName = "Malawi" },
                new Country { Id = 127, HCMCountryCode = "MY", HCMCountryName = "Malaysian", RTWCountryCode = "MYS", RTWCountryName = "Malaysia" },
                new Country { Id = 128, HCMCountryCode = "MV", HCMCountryName = "Maldivian", RTWCountryCode = "MDV", RTWCountryName = "Maldives" },
                new Country { Id = 129, HCMCountryCode = "ML", HCMCountryName = "Malian", RTWCountryCode = "TCD", RTWCountryName = "Mali" },
                new Country { Id = 130, HCMCountryCode = "ML", HCMCountryName = "Malian", RTWCountryCode = "MLI", RTWCountryName = "Mali" },
                new Country { Id = 131, HCMCountryCode = "MT", HCMCountryName = "Maltese", RTWCountryCode = "MLT", RTWCountryName = "Malta" },
                new Country { Id = 132, HCMCountryCode = "MH", HCMCountryName = "Marshallese", RTWCountryCode = "MHL", RTWCountryName = "Marshall Islands" },
                new Country { Id = 133, HCMCountryCode = "MHR_MARTINICAN", HCMCountryName = "Martinican", RTWCountryCode = "MTQ", RTWCountryName = "Martinique" },
                new Country { Id = 134, HCMCountryCode = "MR", HCMCountryName = "Mauritanian", RTWCountryCode = "MRT", RTWCountryName = "Mauritania" },
                new Country { Id = 135, HCMCountryCode = "MU", HCMCountryName = "Mauritian", RTWCountryCode = "MUS", RTWCountryName = "Mauritius" },
                new Country { Id = 136, HCMCountryCode = "MHR_MAYOTTE", HCMCountryName = "Mayotte", RTWCountryCode = "MYT", RTWCountryName = "Mayott" },
                new Country { Id = 137, HCMCountryCode = "MX", HCMCountryName = "Mexican", RTWCountryCode = "MEX", RTWCountryName = "Mexico" },
                new Country { Id = 138, HCMCountryCode = "FM", HCMCountryName = "Micronesian", RTWCountryCode = "FSM", RTWCountryName = "Micronesia" },
                new Country { Id = 139, HCMCountryCode = "MD", HCMCountryName = "Moldovan", RTWCountryCode = "MDA", RTWCountryName = "Moldova" },
                new Country { Id = 140, HCMCountryCode = "MHR_MONACAN", HCMCountryName = "Monacan", RTWCountryCode = "MCO", RTWCountryName = "Monaco" },
                new Country { Id = 141, HCMCountryCode = "MN", HCMCountryName = "Mongolian", RTWCountryCode = "MNG", RTWCountryName = "Mongolia" },
                new Country { Id = 142, HCMCountryCode = "ME", HCMCountryName = "Montenegrin", RTWCountryCode = "MNE", RTWCountryName = "Montenegro" },
                new Country { Id = 143, HCMCountryCode = "MHR_MONTSERRATIAN", HCMCountryName = "Montserratian", RTWCountryCode = "MSR", RTWCountryName = "Montserrat" },
                new Country { Id = 144, HCMCountryCode = "MA", HCMCountryName = "Moroccan", RTWCountryCode = "MAR", RTWCountryName = "Morocco" },
                new Country { Id = 145, HCMCountryCode = "MZ", HCMCountryName = "Mozambican", RTWCountryCode = "MOZ", RTWCountryName = "Mozambique" },
                new Country { Id = 146, HCMCountryCode = "MHR_MYANMAR", HCMCountryName = "Myanmar", RTWCountryCode = "BUR", RTWCountryName = "Myanmar" },
                new Country { Id = 147, HCMCountryCode = "MHR_MYANMAR", HCMCountryName = "Myanmar", RTWCountryCode = "MMR", RTWCountryName = "Burma" },
                new Country { Id = 148, HCMCountryCode = "NA", HCMCountryName = "Namibian", RTWCountryCode = "NAM", RTWCountryName = "Namibia" },
                new Country { Id = 149, HCMCountryCode = "NR", HCMCountryName = "Nauruan", RTWCountryCode = "NRU", RTWCountryName = "Nauru" },
                new Country { Id = 150, HCMCountryCode = "NP", HCMCountryName = "Nepalese", RTWCountryCode = "NPL", RTWCountryName = "Nepal" },
                new Country { Id = 151, HCMCountryCode = "NL", HCMCountryName = "Dutch", RTWCountryCode = "NLD", RTWCountryName = "Netherlands" },
                new Country { Id = 152, HCMCountryCode = "MHR_NETHERLANDS_ANTILLES", HCMCountryName = "Netherlands Antilles", RTWCountryCode = "ANT", RTWCountryName = "Netherlands Antilles" },
                new Country { Id = 153, HCMCountryCode = "MHR_NEW_CALEDONIAN", HCMCountryName = "New Caledonian", RTWCountryCode = "NCL", RTWCountryName = "New Caledonia" },
                new Country { Id = 154, HCMCountryCode = "NZ", HCMCountryName = "New Zealand", RTWCountryCode = "NZL", RTWCountryName = "New Zealand" },
                new Country { Id = 155, HCMCountryCode = "NI", HCMCountryName = "Nicaraguan", RTWCountryCode = "NIC", RTWCountryName = "Nicaragua" },
                new Country { Id = 156, HCMCountryCode = "NE", HCMCountryName = "Nigerien", RTWCountryCode = "NER", RTWCountryName = "Niger" },
                new Country { Id = 157, HCMCountryCode = "NG", HCMCountryName = "Nigerian", RTWCountryCode = "NGA", RTWCountryName = "Nigeria" },
                new Country { Id = 158, HCMCountryCode = "MHR_NIUEAN", HCMCountryName = "Niuean", RTWCountryCode = "NIU", RTWCountryName = "Niue" },
                new Country { Id = 159, HCMCountryCode = "MHR_NORFOLK_ISLANDS", HCMCountryName = "Norfolk Islands", RTWCountryCode = "NFK", RTWCountryName = "Norfolk Island" },
                new Country { Id = 160, HCMCountryCode = "MHR_NORTHERN_MARIANNA_ISLANDS", HCMCountryName = "Northern Marianna Islands", RTWCountryCode = "MNP", RTWCountryName = "Northern Mariana Islands" },
                new Country { Id = 161, HCMCountryCode = "MK", HCMCountryName = "Macedonian", RTWCountryCode = "MKD", RTWCountryName = "Macedonia" },
                new Country { Id = 162, HCMCountryCode = "NO", HCMCountryName = "Norwegian", RTWCountryCode = "NOR", RTWCountryName = "Norway" },
                new Country { Id = 163, HCMCountryCode = "OM", HCMCountryName = "Omani", RTWCountryCode = "OMN", RTWCountryName = "Oman" },
                new Country { Id = 164, HCMCountryCode = "PK", HCMCountryName = "Pakistani", RTWCountryCode = "PAK", RTWCountryName = "Pakistan" },
                new Country { Id = 165, HCMCountryCode = "PW", HCMCountryName = "Palauan", RTWCountryCode = "PLW", RTWCountryName = "Palau" },
                new Country { Id = 166, HCMCountryCode = "PS", HCMCountryName = "Palestinian", RTWCountryCode = "PSE", RTWCountryName = "Palestine" },
                new Country { Id = 167, HCMCountryCode = "PA", HCMCountryName = "Panamanian", RTWCountryCode = "PAN", RTWCountryName = "Panama" },
                new Country { Id = 168, HCMCountryCode = "PG", HCMCountryName = "Papua New Guinean", RTWCountryCode = "PNG", RTWCountryName = "Papua New Guinea" },
                new Country { Id = 169, HCMCountryCode = "PY", HCMCountryName = "Paraguayan", RTWCountryCode = "PRY", RTWCountryName = "Paraguay" },
                new Country { Id = 170, HCMCountryCode = "PE", HCMCountryName = "Peruvian", RTWCountryCode = "PER", RTWCountryName = "Peru" },
                new Country { Id = 171, HCMCountryCode = "PH", HCMCountryName = "Filipino", RTWCountryCode = "PHL", RTWCountryName = "Philippines" },
                new Country { Id = 172, HCMCountryCode = "MHR_PITCAIRN", HCMCountryName = "Pitcairn", RTWCountryCode = "PCN", RTWCountryName = "Pitcairn" },
                new Country { Id = 173, HCMCountryCode = "PL", HCMCountryName = "Polish", RTWCountryCode = "POL", RTWCountryName = "Poland" },
                new Country { Id = 174, HCMCountryCode = "PT", HCMCountryName = "Portuguese", RTWCountryCode = "PRT", RTWCountryName = "Portugal" },
                new Country { Id = 175, HCMCountryCode = "PR", HCMCountryName = "Puerto Rican", RTWCountryCode = "PRI", RTWCountryName = "Puerto Rico" },
                new Country { Id = 176, HCMCountryCode = "QA", HCMCountryName = "Qatari", RTWCountryCode = "QAT", RTWCountryName = "Qatar" },
                new Country { Id = 177, HCMCountryCode = "MHR_REUNIONESE", HCMCountryName = "Reunionese", RTWCountryCode = "REU", RTWCountryName = "Reunion" },
                new Country { Id = 178, HCMCountryCode = "RO", HCMCountryName = "Romanian", RTWCountryCode = "ROU", RTWCountryName = "Romania" },
                new Country { Id = 179, HCMCountryCode = "RU", HCMCountryName = "Russian", RTWCountryCode = "RUS", RTWCountryName = "Russia" },
                new Country { Id = 180, HCMCountryCode = "RW", HCMCountryName = "Rwandan", RTWCountryCode = "RWA", RTWCountryName = "Rwanda" },
                new Country { Id = 181, HCMCountryCode = "MHR_SAINT_HELENA", HCMCountryName = "Saint Helena", RTWCountryCode = "SHN", RTWCountryName = "Saint Helena" },
                new Country { Id = 182, HCMCountryCode = "MHR_SAINT_KITTS_AND_NEVIS", HCMCountryName = "Saint Kitts and Nevis", RTWCountryCode = "KNA", RTWCountryName = "Saint Kitts & Nevis" },
                new Country { Id = 183, HCMCountryCode = "MHR_SAINT_LUCIA", HCMCountryName = "Saint Lucia", RTWCountryCode = "LCA", RTWCountryName = "Saint Lucia" },
                new Country { Id = 184, HCMCountryCode = "MHR_SAINT_PIERRE_AND_MIQUELON", HCMCountryName = "Saint-Pierre and Miquelon", RTWCountryCode = "SPM", RTWCountryName = "Saint Pierre et Miquelon" },
                new Country { Id = 185, HCMCountryCode = "MHR_ST_VINCENT_AND_GRENADINES", HCMCountryName = "St. Vincent and Grenadines", RTWCountryCode = "VCT", RTWCountryName = "Saint Vincent & the Grenadines" },
                new Country { Id = 186, HCMCountryCode = "WS", HCMCountryName = "Samoan", RTWCountryCode = "ASM", RTWCountryName = "Samoa" },
                new Country { Id = 187, HCMCountryCode = "WS", HCMCountryName = "Samoan", RTWCountryCode = "WSM", RTWCountryName = "Samoa" },
                new Country { Id = 188, HCMCountryCode = "SM", HCMCountryName = "Sammarinese", RTWCountryCode = "SMR", RTWCountryName = "San Marino" },
                new Country { Id = 189, HCMCountryCode = "MHR_SAO_TOMIE_AND_PRINCIPE", HCMCountryName = "Sao Tomie and Principe", RTWCountryCode = "STP", RTWCountryName = "Sao Tome et Principe" },
                new Country { Id = 190, HCMCountryCode = "SA", HCMCountryName = "Saudi", RTWCountryCode = "SAU", RTWCountryName = "Saudi Arabia" },
                new Country { Id = 191, HCMCountryCode = "SN", HCMCountryName = "Senegalese", RTWCountryCode = "SEN", RTWCountryName = "Senegal" },
                new Country { Id = 192, HCMCountryCode = "RS", HCMCountryName = "Serbian", RTWCountryCode = "SRB", RTWCountryName = "Serbia" },
                new Country { Id = 193, HCMCountryCode = "SC", HCMCountryName = "Seychellois", RTWCountryCode = "SYC", RTWCountryName = "Seychelles" },
                new Country { Id = 194, HCMCountryCode = "SL", HCMCountryName = "Sierra Leonan", RTWCountryCode = "SLE", RTWCountryName = "Sierra Leone" },
                new Country { Id = 195, HCMCountryCode = "SG", HCMCountryName = "Singapore", RTWCountryCode = "SGP", RTWCountryName = "Singapore" },
                new Country { Id = 196, HCMCountryCode = "SK", HCMCountryName = "Slovak", RTWCountryCode = "SVK", RTWCountryName = "Slovakia" },
                new Country { Id = 197, HCMCountryCode = "SI", HCMCountryName = "Slovenian", RTWCountryCode = "SVN", RTWCountryName = "Slovenia" },
                new Country { Id = 198, HCMCountryCode = "SB", HCMCountryName = "Solomon Islander", RTWCountryCode = "SLB", RTWCountryName = "Solomon Islands" },
                new Country { Id = 199, HCMCountryCode = "SO", HCMCountryName = "Somali", RTWCountryCode = "SOM", RTWCountryName = "Somalia" },
                new Country { Id = 200, HCMCountryCode = "ZA", HCMCountryName = "South African", RTWCountryCode = "ZAF", RTWCountryName = "South africa" },
                new Country { Id = 201, HCMCountryCode = "MHR_GEORGIA_SANDWICH", HCMCountryName = "South Georgia and South Sandwich Islands", RTWCountryCode = "SGS", RTWCountryName = "South Georgia" },
                new Country { Id = 202, HCMCountryCode = "MHR_SOUTH_SUDANESE", HCMCountryName = "South Sudanese", RTWCountryCode = "SSD", RTWCountryName = "South Sudan" },
                new Country { Id = 203, HCMCountryCode = "ES", HCMCountryName = "Spanish", RTWCountryCode = "ESP", RTWCountryName = "Spain" },
                new Country { Id = 204, HCMCountryCode = "LK", HCMCountryName = "Sri Lankan", RTWCountryCode = "LKA", RTWCountryName = "Sri Lanka" },
                new Country { Id = 205, HCMCountryCode = "SD", HCMCountryName = "Sudanese", RTWCountryCode = "SDN", RTWCountryName = "Sudan" },
                new Country { Id = 206, HCMCountryCode = "SR", HCMCountryName = "Surinamese", RTWCountryCode = "SUR", RTWCountryName = "Suriname" },
                new Country { Id = 207, HCMCountryCode = "MHR_SVALBARD_JAN_MAYEN", HCMCountryName = "Svalbard and Jan Mayen Islands", RTWCountryCode = "SJM", RTWCountryName = "Svalbard & Jan Mayen Islands" },
                new Country { Id = 208, HCMCountryCode = "SE", HCMCountryName = "Swedish", RTWCountryCode = "SWE", RTWCountryName = "Sweden" },
                new Country { Id = 209, HCMCountryCode = "CH", HCMCountryName = "Swiss", RTWCountryCode = "CHE", RTWCountryName = "Switzerland" },
                new Country { Id = 210, HCMCountryCode = "SY", HCMCountryName = "Syrian", RTWCountryCode = "SYR", RTWCountryName = "Syria" },
                new Country { Id = 211, HCMCountryCode = "MHR_TAIWANESE", HCMCountryName = "Taiwanese", RTWCountryCode = "TWN", RTWCountryName = "Taiwan" },
                new Country { Id = 212, HCMCountryCode = "TJ", HCMCountryName = "Tajikistani", RTWCountryCode = "TJK", RTWCountryName = "Tajikistan" },
                new Country { Id = 213, HCMCountryCode = "TZ", HCMCountryName = "Tanzanian", RTWCountryCode = "TZA", RTWCountryName = "Tanzania" },
                new Country { Id = 214, HCMCountryCode = "TH", HCMCountryName = "Thai", RTWCountryCode = "THA", RTWCountryName = "Thailand" },
                new Country { Id = 215, HCMCountryCode = "TL", HCMCountryName = "Timorese", RTWCountryCode = "TLS", RTWCountryName = "Timor-Leste" },
                new Country { Id = 216, HCMCountryCode = "TG", HCMCountryName = "Togolese", RTWCountryCode = "TGO", RTWCountryName = "Togo" },
                new Country { Id = 217, HCMCountryCode = "MHR_TOKELAU", HCMCountryName = "Tokelau", RTWCountryCode = "TKL", RTWCountryName = "Tokelau" },
                new Country { Id = 218, HCMCountryCode = "TO", HCMCountryName = "Tongan", RTWCountryCode = "TON", RTWCountryName = "Tonga" },
                new Country { Id = 219, HCMCountryCode = "TT", HCMCountryName = "Trinidadian", RTWCountryCode = "TTO", RTWCountryName = "Trinidad & Tobago" },
                new Country { Id = 220, HCMCountryCode = "TN", HCMCountryName = "Tunisian", RTWCountryCode = "TUN", RTWCountryName = "Tunisia" },
                new Country { Id = 221, HCMCountryCode = "TR", HCMCountryName = "Turkish", RTWCountryCode = "TUR", RTWCountryName = "Turkey" },
                new Country { Id = 222, HCMCountryCode = "TM", HCMCountryName = "Turkmen", RTWCountryCode = "TKM", RTWCountryName = "Turkmenistan" },
                new Country { Id = 223, HCMCountryCode = "MHR_TURK_AND_CAICOS", HCMCountryName = "Turk and Caicos Islands", RTWCountryCode = "TCA", RTWCountryName = "Turks & Caicos Islands" },
                new Country { Id = 224, HCMCountryCode = "TV", HCMCountryName = "Tuvaluan", RTWCountryCode = "TUV", RTWCountryName = "Tuvalu" },
                new Country { Id = 225, HCMCountryCode = "UG", HCMCountryName = "Ugandan", RTWCountryCode = "UGA", RTWCountryName = "Uganda" },
                new Country { Id = 226, HCMCountryCode = "UA", HCMCountryName = "Ukrainian", RTWCountryCode = "UKR", RTWCountryName = "Ukraine" },
                new Country { Id = 227, HCMCountryCode = "AE", HCMCountryName = "Emirati", RTWCountryCode = "ARE", RTWCountryName = "UAE" },
                new Country { Id = 228, HCMCountryCode = "GB", HCMCountryName = "British", RTWCountryCode = "GBR", RTWCountryName = "United Kingdom" },
                new Country { Id = 234, HCMCountryCode = "US", HCMCountryName = "American", RTWCountryCode = "USA", RTWCountryName = "United States" },
                new Country { Id = 235, HCMCountryCode = "MHR_US_MINOR_OURLYING", HCMCountryName = "United States Minor Ourlying Islands", RTWCountryCode = "UMI", RTWCountryName = "United States Minor Outlying Islands" },
                new Country { Id = 236, HCMCountryCode = "UY", HCMCountryName = "Uruguayan", RTWCountryCode = "URY", RTWCountryName = "Uruguay" },
                new Country { Id = 237, HCMCountryCode = "UZ", HCMCountryName = "Uzbekistani", RTWCountryCode = "UZB", RTWCountryName = "Uzbekistan" },
                new Country { Id = 238, HCMCountryCode = "MHR_VANUATUAN", HCMCountryName = "Vanuatuan", RTWCountryCode = "VUT", RTWCountryName = "Vanuatu" },
                new Country { Id = 239, HCMCountryCode = "VE", HCMCountryName = "Venezuelan", RTWCountryCode = "VEN", RTWCountryName = "Venezuela" },
                new Country { Id = 240, HCMCountryCode = "VN", HCMCountryName = "Vietnamese", RTWCountryCode = "VNM", RTWCountryName = "Vietnam" },
                new Country { Id = 241, HCMCountryCode = "MHR_BRITISH_VIRGIN_ISLANDS", HCMCountryName = "British Virgin Islands", RTWCountryCode = "VGB", RTWCountryName = "Virgin Islands (British)" },
                new Country { Id = 242, HCMCountryCode = "VG", HCMCountryName = "Virgin Islander", RTWCountryCode = "VIR", RTWCountryName = "Virgin Islands (US)" },
                new Country { Id = 243, HCMCountryCode = "MHR_WALLISIAN", HCMCountryName = "Wallisian", RTWCountryCode = "WLF", RTWCountryName = "Wallis & Futuna Islands" },
                new Country { Id = 244, HCMCountryCode = "EH", HCMCountryName = "Sahrawi", RTWCountryCode = "ESH", RTWCountryName = "Western Sahara" },
                new Country { Id = 245, HCMCountryCode = "YE", HCMCountryName = "Yemeni", RTWCountryCode = "YEM", RTWCountryName = "Yemen" },
                new Country { Id = 246, HCMCountryCode = "ZM", HCMCountryName = "Zambian", RTWCountryCode = "ZMB", RTWCountryName = "Zambia" },
                new Country { Id = 247, HCMCountryCode = "ZW", HCMCountryName = "Zimbabwean", RTWCountryCode = "ZWE", RTWCountryName = "Zimbabwe" },
                new Country { Id = 248, HCMCountryCode = "ZW", HCMCountryName = "Zimbabwean", RTWCountryCode = "ZIM", RTWCountryName = "Zimbabwe" },
                new Country { Id = 249, HCMCountryCode = "VA", HCMCountryName = "Vatican Citizen", RTWCountryCode = "VAT", RTWCountryName = "Vatican City" },
                new Country { Id = 250, HCMCountryCode = "SZ", HCMCountryName = "Swazi", RTWCountryCode = "SWZ", RTWCountryName = "Swaziland" }
                );
        }

        private static void SeedStatusData(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Status>().HasData(
               new Status { Id = 1, StatusName = "CheckNotCompleted", ExternalValue = "CheckNotCompleted" },
               new Status { Id = 2, StatusName = "Successful", ExternalValue = "Successful" },
               new Status { Id = 3, StatusName = "Failed", ExternalValue = "Failed" },
               new Status { Id = 4, StatusName = "PartialCheck", ExternalValue = "PartialCheck" },
               new Status { Id = 5, StatusName = "UserRemovedCheck", ExternalValue = "UserRemovedCheck" },
               new Status { Id = 6, StatusName = "SystemRemovedCheck", ExternalValue = "SystemRemovedCheck" }

            );
        }

        private static void SeedStagesData(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Stage>().HasData(
               new Stage { Id = 1, StageName = "Initial Stage" },
               new Stage { Id = 2, StageName = "Check Requested" },
               new Stage { Id = 3, StageName = "Check Completed" },
               new Stage { Id = 4, StageName = "HCM Updated" },
               new Stage { Id = 5, StageName = "Check Request Failed" },
               new Stage { Id = 6, StageName = "Read Data Failed" },
               new Stage { Id = 7, StageName = "HCM Update Failed" },
               new Stage { Id = 8, StageName = "HCM Documents Uploaded" },
               new Stage { Id = 9, StageName = "HCM Documents Upload Failed" },
               new Stage { Id = 10, StageName = "Passport Patch Failed" },
               new Stage { Id = 11, StageName = "Passport Patch Ignored" },
               new Stage { Id = 12, StageName = "Passport Patch Completed" }
            );
        }

        public static void SeedIncidentDetails(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IncidentDetail>().HasData(
            new IncidentDetail
            {
                Id = 1,
                ErrorCode = "AZRCCP_RTW_HR_APP_101001",
                Impact = 3,
                Active = true,
                Type = IncidentType.Application,
                AssignmentGroup = "HR Engineering",
                Description = "Azure EventHub Error",
                ConfigurationItem = "Cloud Colleague Publisher",
                UndefinedCaller = "HR Engineering",
                Summary = "Azure resource error. Please follow the PDG AZRCCP_RTW_HR_APP_101001.",
                BusinessService = "Application Platform",
                UndefinedLocation = "Application Platform",
            },

            new IncidentDetail
            {
                Id = 2,
                ErrorCode = "AZRCCP_RTW_HR_APP_102001",
                Impact = 3,
                Active = true,
                Type = IncidentType.Application,
                AssignmentGroup = "HR Engineering",
                Description = "Azure Database Error",
                ConfigurationItem = "Cloud Colleague Publisher",
                UndefinedCaller = "HR Engineering",
                Summary = "Azure Database Error. Please follow the PDG AZRCCP_RTW_HR_APP_102001.",
                BusinessService = "Application Platform",
                UndefinedLocation = "Application Platform",
            },

            new IncidentDetail
            {
                Id = 3,
                ErrorCode = "AZRCCP_RTW_HR_APP_103001",
                Impact = 3,
                Active = true,
                Type = IncidentType.Application,
                AssignmentGroup = "HR Engineering",
                Description = "Azure KeyVault Error",
                ConfigurationItem = "Cloud Colleague Publisher",
                UndefinedCaller = "HR Engineering",
                Summary = "Azure KeyVault Error. Please follow the PDG AZRCCP_RTW_HR_APP_103001.",
                BusinessService = "Application Platform",
                UndefinedLocation = "Application Platform",
            },

            new IncidentDetail
            {
                Id = 4,
                ErrorCode = "AZRCCP_RTW_HR_APP_104001",
                Impact = 3,
                Active = true,
                Type = IncidentType.Data,
                AssignmentGroup = "HR Engineering",
                Description = "RTW Outbound API Error",
                ConfigurationItem = "Cloud Colleague Publisher",
                UndefinedCaller = "HR Engineering",
                Summary = "RTW New starter posting data API Error. Please follow the PDG AZRCCP_RTW_HR_APP_104001.",
                BusinessService = "Application Platform",
                UndefinedLocation = "Application Platform",
            },

            new IncidentDetail
            {
                Id = 5,
                ErrorCode = "AZRCCP_RTW_HR_APP_105001",
                Impact = 3,
                Active = true,
                Type = IncidentType.Data,
                AssignmentGroup = "HR Engineering",
                Description = "RTW Inbound API Error",
                ConfigurationItem = "Cloud Colleague Publisher",
                UndefinedCaller = "HR Engineering",
                Summary = "RTW Read data API Error. Please follow the PDG AZRCCP_RTW_HR_APP_105001.",
                BusinessService = "Application Platform",
                UndefinedLocation = "Application Platform",
            },

            new IncidentDetail
            {
                Id = 6,
                ErrorCode = "AZRCCP_RTW_HR_APP_106001",
                Impact = 3,
                Active = true,
                Type = IncidentType.Data,
                AssignmentGroup = "HR Engineering",
                Description = "RTW Data Error",
                ConfigurationItem = "Cloud Colleague Publisher",
                UndefinedCaller = "HR Engineering",
                Summary = "Update HCM Data Error. Please follow the PDG AZRCCP_RTW_HR_APP_106001.",
                BusinessService = "Application Platform",
                UndefinedLocation = "Application Platform",
            },
             new IncidentDetail
             {
                 Id = 7,
                 ErrorCode = "AZRCCP_RTW_HR_APP_110001",
                 Impact = 3,
                 Active = true,
                 Type = IncidentType.Application,
                 AssignmentGroup = "HR Engineering",
                 Description = "Generic Exception",
                 ConfigurationItem = "Cloud Colleague Publisher",
                 UndefinedCaller = "HR Engineering",
                 Summary = "Generic exception. Please follow the PDG AZRCCP_RTW_HR_APP_110001.",
                 BusinessService = "Application Platform",
                 UndefinedLocation = "Application Platform",
             });
        }

        private static void SeedDocumentTypeData(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DocumentType>().HasData(
            new DocumentType { Id = 1, RTWDocumentName = "Application Registration Card - back", HCMDocumentName = "Home Office application/referral evidence", DocumentSection = DocumentSection.OtherDocument },
            new DocumentType { Id = 2, RTWDocumentName = "Application Registration Card - front", HCMDocumentName = "Home Office application/referral evidence", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_ARC_CARD_EMP_PERMIT_ECS", HCMVisaPermitTypeDescription = "ARC Card with Employment Permitted + Positive ECS" },
            new DocumentType { Id = 3, RTWDocumentName = "Biometric Residence card - back", HCMDocumentName = "Biometric Residence Permit current (not Tier 4)", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_BRP_TIME_LTD_LTR", HCMVisaPermitTypeDescription = "Biometric Residence Permit (Current) – Time Limited Leave to Remain" },
            new DocumentType { Id = 4, RTWDocumentName = "Biometric Residence card - front", HCMDocumentName = "Biometric Residence Permit current (not Tier 4)", DocumentSection = DocumentSection.OtherDocument },
            new DocumentType { Id = 5, RTWDocumentName = "Biometric Residence card - Indefinite Leave - front", HCMDocumentName = "Biometric Residence Permit current (not Tier 4)", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_BRP_ILR", HCMVisaPermitTypeDescription = "Biometric Residence Permit (Current) - Indefinite Leave to Remain" },
            new DocumentType { Id = 6, RTWDocumentName = "Biometric Residence card - Permanent Residence (EEA) - front", HCMDocumentName = "EEA Identity Card", DocumentSection = DocumentSection.OtherDocument },
            new DocumentType { Id = 7, RTWDocumentName = "Biometric Residence Card - Tier 4 (student) - front", HCMDocumentName = "Biometric Residence Permit current (Tier 4) plus study & term time evidence", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_STUDENT_VISA", HCMVisaPermitTypeDescription = "Student Visa" },
            new DocumentType { Id = 8, RTWDocumentName = "Birth or Adoption Certificate", HCMDocumentName = "Birth Certificate British (full) plus NI No.", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_BIRTH_ADOPTION_CI_IOM_NI", HCMVisaPermitTypeDescription = "Birth/Adoption Certificate issued in UK, Channel Islands, Isle of Man + NI Numbe" },
            new DocumentType { Id = 9, RTWDocumentName = "Birth, Adoption or Naturalisation Certificate", HCMDocumentName = "Birth Certificate British (full) plus NI No.", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_BIRTH_ADOPTION_CI_IOM_NI", HCMVisaPermitTypeDescription = "Birth/Adoption Certificate issued in UK, Channel Islands, Isle of Man + NI Numbe" },
            new DocumentType { Id = 10, RTWDocumentName = "Certificate of Application Family Member - back", HCMDocumentName = "Home Office application/referral evidence", DocumentSection = DocumentSection.OtherDocument },
            new DocumentType { Id = 11, RTWDocumentName = "Certificate of Application Family Member - front", HCMDocumentName = "Home Office application/referral evidence", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_COA_HOME_OFF_APPLICATION", HCMVisaPermitTypeDescription = "Certificate of Application (Home Office Application)" },
            new DocumentType { Id = 12, RTWDocumentName = "ECS Positive Verification Notice", HCMDocumentName = "Home Office application/referral evidence", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_COA_HOME_OFF_APPLICATION", HCMVisaPermitTypeDescription = "Certificate of Application (Home Office Application)" },
            new DocumentType { Id = 13, RTWDocumentName = "ECS Positive Verification Notice - Asylum", HCMDocumentName = "Home Office application/referral evidence", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_COA_HOME_OFF_APPLICATION", HCMVisaPermitTypeDescription = "Certificate of Application (Home Office Application)" },
            new DocumentType { Id = 14, RTWDocumentName = "ECS Positive Verification Notice - Family", HCMDocumentName = "Home Office application/referral evidence", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_COA_HOME_OFF_APPLICATION", HCMVisaPermitTypeDescription = "Certificate of Application (Home Office Application)" },
            new DocumentType { Id = 15, RTWDocumentName = "Frontier Worker Permit", HCMDocumentName = "EEA Identity Card", DocumentSection = DocumentSection.OtherDocument },
            new DocumentType { Id = 16, RTWDocumentName = "Immigration Status Document - Indefinite Leave to Enter or Remain", HCMDocumentName = "Immigration Status Document plus NI No.", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_IMMIGRATION_STATUS_DOC_ILR", HCMVisaPermitTypeDescription = "Immigration Status Document - Indefinite Leave to Remain + NI Number" },
            new DocumentType { Id = 17, RTWDocumentName = "Immigration Status Document - Leave to Enter or Remain", HCMDocumentName = "Immigration Status Document plus NI No.", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_IMMIGRATION_STATUS_DOC_ILR", HCMVisaPermitTypeDescription = "Immigration Status Document - Indefinite Leave to Remain + NI Number" },
            new DocumentType { Id = 18, RTWDocumentName = "Immigration Status Document - Work Permit", HCMDocumentName = "Immigration Status Document plus NI No.", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_IMMIGRATION_STATUS_DOC_ILR", HCMVisaPermitTypeDescription = "Immigration Status Document - Indefinite Leave to Remain + NI Number" },
            new DocumentType { Id = 19, RTWDocumentName = "Marriage certificate, divorce decree absolute, a deed poll or statutory declaration", HCMDocumentName = "Marriage Certificate", DocumentSection = DocumentSection.OtherDocument },
            new DocumentType { Id = 20, RTWDocumentName = "National Insurance Document", HCMDocumentName = "Birth Certificate British (full) plus NI No.", DocumentSection = DocumentSection.OtherDocument },
            new DocumentType { Id = 21, RTWDocumentName = "Naturalisation Certificate", HCMDocumentName = "Certificate of Registration or Naturalisation plus NI No.", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_CERT_REGISTRATION_NI", HCMVisaPermitTypeDescription = "Certificate of Registration or Naturalisation as a British Citizen + NI Number" },
            new DocumentType { Id = 22, RTWDocumentName = "Passport", HCMDocumentName = "Passport (British)", DocumentSection = DocumentSection.Passport },
            new DocumentType { Id = 23, RTWDocumentName = "Passport Additional Page", HCMDocumentName = "Passport (British)", DocumentSection = DocumentSection.OtherDocument },
            new DocumentType { Id = 24, RTWDocumentName = "Passport Stamp - Indefinite Leave to Enter or Remain", HCMDocumentName = "Visa current within valid passport (not Tier 4)", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_IMMIGRATION_STATUS_DOC_ILR", HCMVisaPermitTypeDescription = "Immigration Status Document - Indefinite Leave to Remain + NI Number" },
            new DocumentType { Id = 25, RTWDocumentName = "Passport Stamp - Leave to Enter or Remain", HCMDocumentName = "Visa current within valid passport (not Tier 4)", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_IMMIGRATION_STATUS_DOC_ILR", HCMVisaPermitTypeDescription = "Immigration Status Document - Indefinite Leave to Remain + NI Number" },
            new DocumentType { Id = 26, RTWDocumentName = "Passport Stamp - Right of Abode", HCMDocumentName = "Visa current within valid passport (not Tier 4)", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_RIGHT_TO_ABODE", HCMVisaPermitTypeDescription = "Right to Abode (Current)" },
            new DocumentType { Id = 27, RTWDocumentName = "Passport Stamp - Tier 4 (student)", HCMDocumentName = "Visa current within valid passport (Tier 4) plus study & term time evidence", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_STUDENT_VISA", HCMVisaPermitTypeDescription = "Student Visa" },
            new DocumentType { Id = 28, RTWDocumentName = "Passport Stamp - Work Permit", HCMDocumentName = "Visa current within valid passport (not Tier 4)", DocumentSection = DocumentSection.Visa, HCMVisaPermitTypeCode = "MHR_TIER_1_GENERAL_VISA", HCMVisaPermitTypeDescription = "Tier 1 General Visa" },
            new DocumentType { Id = 29, RTWDocumentName = "Share Code Evidence", HCMDocumentName = "EEA Identity Card", DocumentSection = DocumentSection.ShareCode },
            new DocumentType { Id = 30, RTWDocumentName = "Student Term Time Evidence", HCMDocumentName = "Biometric Residence Permit current (Tier 4) plus study & term time evidence", DocumentSection = DocumentSection.OtherDocument }
          );
        }
    }
}
